server:
  port: 80

spring:
  servlet:
    multipart:
      max-file-size: 8Mb
      max-request-size: 10Mb
  #开发工具
  devtools:
    restart:
      #热部署生效 
      enabled: true
      #设置重启的目录
      additional-paths: src/main/java
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://47.114.142.152:3506/script_dev?useUnicode=true&characterEncoding=utf8&useSSL=false
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: AliMysql123456
#    url: jdbc:oracle:thin:@192.168.2.75:1521:orcl 
#    driverClassName: oracle.jdbc.OracleDriver
#    username: summary
#    password: summary
#  redis:
#    host: 192.168.2.71
#    port: 6379
#    timeout: 3000
  freemarker:
    allow-request-override: false
    cache: false
    check-template-location: true
    suffix: .html
    charset: UTF-8
    content-type: text/html; charset=utf-8
    template-loader-path: /WEB-INF/page/
  mail:
    host: smtp.qq.com #发送邮件服务器
    username: 460736903@qq.com #发送邮件的邮箱地址
    password:  etftrpgocvenbieg #客户端授权码，不是邮箱密码，这个在qq邮箱设置里面自动生成的
    properties.mail.smtp.port: 465 #端口号465或587
    from: 460736903@qq.com # 发送邮件的地址，和上面username一致
    to: zhenyuan.bi@supwisdom.com
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8

#=============【log】====================
logging:
  config: classpath:logback/logback-spring-dev-colorful.xml
  level:
    pro.bzy.boot: debug 


#=============【mybatis】====================
mybatis-plus:
  #配置
  configuration:
    #二级缓存
    cache-enabled: true
    
    


#=============【系统变量】==================== 
app:
  page-constant:
    login-title: 登陆
    script-name: 图灵屋
  #配置
  config:  
    log: 
      systemlog-archive-dictPath: D:/logArchive/system/
    # 接口文档参数
    swagger2: 
      enable: true
      title: 接口文档
      desc: 接口文档描述
      base-package: pro.bzy
      server-url: http://localhost:${server.port}
    # 缓存配置变量
    cache:
      use: ehcache
      ehcache:
        max-elements-inMemory: 5000
        overflow-to-disk: false
        eternal: false
        time-to-live-seconds: 0
        time-to-idle-seconds: 600
    # 定时器配置
    timer:
      thread-pool-size: 8
      thread-prefix: ScheduleTask-
    # shiro权限认证
    shiro:
      login-url: /login
      success-url: bbb
      authen-timeout: 1800000
    #jwt
    jwt:
      access-token-expire: 30 #单位s 时长30秒
      refresh-token-expire: 1500 #单位s 时长5分钟
    #微信小程序
    wechat:
      appid: wx8bd311e96b811193
      secret: 1c1c74780e6161dc47ce3aac544f0350
    #图片服务
    image-server:
      server: /imageServer
      base-storage-path: F:/${app.config.image-server.server}
      user-avatar-image-path: /userAvatar/
      juben-cover-image-path: /juben/covers/
      juben-character-image-path: /juben/characters/
      juben-bulletin-icon-image-path: /juben/icon/
      
    

