#=============【server】====================
server:
  port: 80



#=============【spring】==================== 
spring:
  #启用的主文件
  profiles:
    active: prod
  # 缓存
  cache:
    # ehcache
    ehcache:
      config: classpath:cache/ehcache.xml
  mvc: 
    view:
      prefix: /WEB-INF/page/
      suffix: .html
    resources:
      static-locations: 
      
      
#=============【mybatis】====================
mybatis-plus:
  config-locations: 
  mapper-locations: 
  type-aliases-package: 
  #配置
  configuration:
    map-underscore-to-camel-case: true #驼峰式命名 
    #二级缓存
    #cache-enabled: false
  
  
  
